- name: Pre-build dev container image
  uses: devcontainers/ci@v0.3
  with:
    imageName: ghcr.io/SATVILab/CompACSCyTOFTCells
    cacheFrom: ghcr.io/SATVILab/CompACSCyTOFTCells
    refFilterForPush: main
    eventFilterForPush: main
